---
# tasks file for roles/proxy

  - name: Create proxy container and connect to network
    docker_container:
      name: httpd
      image: simonmachadocpe/httpd
      networks:
        - name: app-network
      ports: 
        - 80:80      
