name: CI devops 2023
on:
  push:
    branches: main
  pull_request: null
jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.5.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Build and test with Maven
        run: cd ./docker-compose/simple-api && mvn clean verify
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api
          tags: ${{secrets.DOCKERHUB_LOGIN}}/backend:latest
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: ${{secrets.DOCKERHUB_LOGIN}}/database:latest
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./httpd
          tags: ${{secrets.DOCKERHUB_LOGIN}}/httpd:latest
